title: SEBS Scholarship

description: >-
  The SEBS Scholarship is open to all seniors graduating from SEBS at Pueblo County High School.
  The SEBS Scholarship Foundation is a non-profit public charity dedicated to helping SEBS students afford to further
  their education by providing yearly scholarships to graduating SEBS seniors who demonstrate characteristics that align
  with our core values.

url: "https://sebsscholarship.org"

repo: sebs-scholarship/Website

baseurl: ""

plugins:
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "assets"
    values:
      sitemap: false
  -
    scope:
      path: "admin"
    values:
      sitemap: false

remote_theme: sebs-scholarship/Theme@31ad5b

analytics_id: G-DCKNB7HP7R

exclude:
  - .github
  - composer.*
  - README.md
  - Gemfile
  - Gemfile.lock
  - scripts