name: sebs-website

services:
  serve:
    build:
      context: ./docker/jekyll
    command:
      - /bin/bash
      - -c
      - |
        set -e
        bundle install
        bundle exec jekyll serve --host 0.0.0.0 --future --drafts $${JEKYLL_XARGS}
    environment:
      JEKYLL_UID: 1001
      JEKYLL_GID: 1001
      JEKYLL_XARGS: ${XARGS:-}
    ports:
      - "4000:4000"
    volumes:
      - type: volume
        source: bundle-cache
        target: /usr/local/bundle
      - type: bind
        source: ./
        target: /srv/jekyll
  build:
    build:
      context: ./docker/jekyll
    command:
      - /bin/bash
      - -c
      - |
        set -e
        bundle install
        bundle exec jekyll build --future $${JEKYLL_XARGS}
    environment:
      JEKYLL_UID: 1001
      JEKYLL_GID: 1001
      JEKYLL_XARGS: ${XARGS:-}
    volumes:
      - type: volume
        source: bundle-cache
        target: /usr/local/bundle
      - type: bind
        source: ./
        target: /srv/jekyll
  composer:
    image: composer:2
    working_dir: /app
    command:
      - install
      - -n
    volumes:
      - type: bind
        source: ./
        target: /app

volumes:
  bundle-cache:
